language: java
dist: trusty

jdk:
  - oraclejdk8

sudo: required

os:
  - linux

before_install:
  - openssl aes-256-cbc -pass pass:$PGP_KEY_PASSWORD -in ./.ci/secring.gpg.enc -out ~/secring.gpg -d -md md5
  - chmod a+x gradlew

script:
  - travis_retry . ./gradlew clean compile 

