plugins {
    id 'org.gradle.toolchains.foojay-resolver-convention' version '0.8.0'
}

include 'aprint-gervill'
include 'aprint-core'
include 'aprint-gui'

//include 'aprint-synth-plugin'

include 'aprint-machine-control'
include 'aprint-machine-control-gui'

include 'aprint-punch-extension'

include 'aprint-book-scanner'
include 'aprint-recognition-extension'

include 'aprint-mcp'

include 'bundle'


rootProject.name = 'APrintProject'
